spring.application.name=T1-FeignGrupo1

server.port=8080

api.jsonplaceholder.url=https://jsonplaceholder.typicode.com
api.fakestore.url=https://fakestoreapi.com
api.rickandmorty.url=https://rickandmortyapi.com/api
